language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.pip

script:
  - pylint --disable superfluous-parens --disable line-too-long --disable fixme --disable global-statement --disable missing-docstring --disable duplicate-code *.py
